macro(create_k4a_target target_name include_dir library)
  add_library(${target_name} SHARED IMPORTED)
  set_target_properties(${target_name} PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${include_dir}")
  
  set_property(TARGET ${target_name} APPEND PROPERTY IMPORTED_CONFIGURATIONS "RELEASE")
  set_target_properties(${target_name} PROPERTIES IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX")
  if(WIN32)
    set_target_properties(${target_name} PROPERTIES IMPORTED_IMPLIB_RELEASE "${library}")
  else()
    set_target_properties(${target_name} PROPERTIES IMPORTED_LOCATION_RELEASE "${library}")
  endif()

  set_property(TARGET ${target_name} APPEND PROPERTY IMPORTED_CONFIGURATIONS "DEBUG")
  set_target_properties(${target_name} PROPERTIES IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX")
  if(WIN32)
    set_target_properties(${target_name} PROPERTIES IMPORTED_IMPLIB_DEBUG "${library}")
  else()
    set_target_properties(${target_name} PROPERTIES IMPORTED_LOCATION_DEBUG "${library}")
  endif()
endmacro()